# Generated by Django 4.2.7 on 2025-01-10 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MessageHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=128)),
                ('message', models.TextField()),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='MQTTError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(choices=[('mqtt', 'mqtt'), ('ws', 'ws')], max_length=30)),
                ('event', models.CharField(choices=[('connect', 'connect'), ('disconnect', 'disconnect'), ('receive_message', 'receive_message')], max_length=30)),
                ('message', models.TextField()),
                ('error', models.BooleanField()),
                ('time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank='', default='', max_length=128, null='')),
                ('sunlight', models.DecimalField(decimal_places=3, max_digits=6)),
                ('water', models.DecimalField(decimal_places=3, max_digits=6)),
                ('soil_type', models.DecimalField(decimal_places=3, max_digits=6)),
                ('humidity', models.DecimalField(decimal_places=3, max_digits=6)),
                ('active', models.BooleanField(default=False)),
                ('lore', models.TextField()),
                ('date_created', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('humidity', models.DecimalField(decimal_places=3, max_digits=6)),
                ('temperature', models.DecimalField(decimal_places=3, max_digits=6)),
                ('light', models.DecimalField(decimal_places=3, max_digits=6)),
                ('date', models.DateTimeField()),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mqtt.plant')),
            ],
            options={
                'verbose_name_plural': '  Sensor Data',
            },
        ),
    ]
