# Generated by Django 4.2.7 on 2025-01-12 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mqtt', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plant',
            old_name='humidity',
            new_name='maxHumidity',
        ),
        migrations.AddField(
            model_name='plant',
            name='maxTemperature',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plant',
            name='minHumidity',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plant',
            name='minTemperature',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='plant',
            name='sunlight',
            field=models.CharField(blank='', default='', max_length=128, null=''),
        ),
    ]
